<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>        
        <LangVersion>12.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.1.0-beta.0</Version>        
        <Authors>Andrii Marchenko, Anton Moldovan</Authors>
        <Company>NBomber</Company>
        <Copyright>NBomber@2024</Copyright>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>nbomber_icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/PragmaticFlow/NBomber.WebBrowser</RepositoryUrl>
        <PackageTags>webbrowser, load-testing, performance-testing, integration-testing</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Description>NBomber plugin for writing scenarios that using webbrowser testing</Description>
        <Title>NBomber.WebBrowser</Title>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" Visible="false" PackagePath="" />
        <None Include="../../assets/nbomber_icon.png" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.Playwright" Version="1.44.0" />        
        <PackageReference Include="NBomber.Contracts" Version="5.4.0" />
        <PackageReference Include="PuppeteerSharp" Version="18.0.1" />
    </ItemGroup>

</Project>
