<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\NBomber.WebBrowser\NBomber.WebBrowser.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NBomber" Version="6.2.0" />
    </ItemGroup>

</Project>
